### ISSUE TITLE
Missing README.MD

### ISSUE THREAD

**Issue by Atomoox** [Yuyugnat/SidAmongUs#6]
As I was looking for documentation, I was left speechless when I discovered that README.MD is That is a dreadful practice as there is no way to know how to start, install or setup the project at all ?
Please fix so I can use the repo the good way.

Thanks for reading.

**Comment by Rayan-guemar** [comment]
Hi @Atomoox, 
I started a brand new README.MD just waiting for @Yuyugnat to deal with my pull request ( i've been waiting for 
15 days ).
We are very sorry for the inconvenience. 

Best regards. 
SidAmongus inc. dev Team

**Comment by Yuyugnat** [comment]
Since this repo isn't only missing a readme but also missing this ratio, I close this issue
